### ISSUE TITLE
Automatically launch into VR mode

### ISSUE THREAD

**Issue by SteveEdson** [islate/SlateVideo360#10]
Is it possible to modify the constructor with a new parameter for VR mode?

E.g, updating `Video360ViewController *videoController = [[Video360ViewController alloc] initWithNibName:@"HTY360PlayerVC" bundle:nil url:url];` to something like

`Video360ViewController *videoController = [[Video360ViewController alloc] initWithNibName:@"HTY360PlayerVC" bundle:nil url:url vr:true];`

I noticed that `initWithNibName` uses the code within the HTY360 player, so I wasn't sure if it could be modified here.

Thanks

**Comment by linyize** [comment]
Do u mean cardboard mode? You can fork a repo, and modify for your idea. If u like, can open a pullrequest. I will review and accept it.

**Comment by SteveEdson** [comment]
I mean cardboard mode yeah. No problem, I'll see what I can do.

**Comment by tibewww** [comment]
Hi SteveEdson, Did you manage to find a way for this ?

Thanks ;)

**Comment by SteveEdson** [comment]
I basically added the following:

``` obj-c
- (void) setVRModeEnabled:(BOOL)enabled {
    if(enabled) {
        _isUsingCardboard = YES;
    } else {
        _isUsingCardboard = NO;
    }
}
```

And then loaded it with:

``` obj-c
    Video360ViewController *videoController = [[Video360ViewController alloc] initWithNibName:@"HTY360PlayerVC" bundle:nil url:url];

    [videoController setVRModeEnabled:enabled];

    if (![[self presentedViewController] isBeingDismissed]) {
        [self presentViewController:videoController animated:YES completion:nil];
    }
```

**Comment by tibewww** [comment]
Hi, Thanks for answering so fast !

Where do you add the following ? ( I'm starting with Objective C and Xcode...) : 

`- (void) setVRModeEnabled:(BOOL)enabled {
    if(enabled) {
        _isUsingCardboard = YES;
    } else {
        _isUsingCardboard = NO;
    }
}`

Really appreciate !

**Comment by SteveEdson** [comment]
Just under `@implementation Video360ViewController` of the `Video360ViewController` file

**Comment by tibewww** [comment]
Thanks a lot, 

It seems the folowing:

`Video360ViewController *videoController = [[Video360ViewController alloc] initWithNibName:@"HTY360PlayerVC" bundle:nil url:url];
    [videoController setVRModeEnabled:enabled];
    if (![[self presentedViewController] isBeingDismissed]) {
        [self presentViewController:videoController animated:YES completion:nil];
    }`

is giving me an error...

I've calling it in ViewController.m by the following:

`- (IBAction)playFile:(id)sender
{
    NSString *path = [[NSBundle mainBundle] pathForResource:@"demo1" ofType:@"mp4"];
    NSURL *url = [NSURL fileURLWithPath:path];

```
Video360ViewController *videoController = [[Video360ViewController alloc] initWithNibName:@"HTY360PlayerVC" bundle:nil url:url];  

[videoController setVRModeEnabled:enabled];

if (![[self presentedViewController] isBeingDismissed]) {
    [self presentViewController:videoController animated:YES completion:nil];
}}`
```

But it's giving me an error at the following line:

`[videoController setVRModeEnabled:enabled];
`

Saying: No visible @interfacfe for 'Video360ViewController' declares the selector 'SetVRModeEnabled'

Do you have any idea by any chances of what is missing ?

Thanks for all your help and time :)

**Comment by SteveEdson** [comment]
Oh sorry, add

``` obj-c
- (void) setVRModeEnabled:(BOOL) enabled;
```

to Video360ViewController.h inside the `@interface` lines

**Comment by tibewww** [comment]
Hmmm,

Just added and I get still an eror in the ViewController.m same line as before:

`[videoController setVRModeEnabled:enabled];
`

But now it saus "User of undeclared identified 'enabled'

my Video360viewController.h looks like:

```
#import <UIKit/UIKit.h>

#import "HTY360PlayerVC.h"
@interface Video360ViewController : HTY360PlayerVC
- (void) setVRModeEnabled:(BOOL) enabled;
@end
```

Sorry to be a pain :)

**Comment by SteveEdson** [comment]
`enabled` is just a boolean that i've passed in from somewhere else. So just pass in your own variable, or set it to `true` / `Yes`.

In the .m file, leave the .h as it is

**Comment by tibewww** [comment]
Hi Steve,

Thanks, It's what I've been trying, to setup to true instead of enable. Which is fine, now it start the app. But it play the Video in 360 by default and not in Cardboard mode unfortunatly :(

Any idea why?

**Comment by SteveEdson** [comment]
I think I had to trigger a cardbutton button press event on the viewDidLoad so that it takes the new setting

**Comment by tibewww** [comment]
Hm, I'm not sur to understand this :/

**Comment by linyize** [comment]
@SteveEdson Great job! Can u request a pull?

**Comment by tibewww** [comment]
HI Steve, If by any chance you have time, can you let me know how tou trigger a cardbutton in the ViewDidLoad ? I suppose it's in the file Video360ViewController.m in the following:

```
- (void)viewDidLoad
{
    [super viewDidLoad];

    [self configureCardboardButton];
}
```

Thanks for your help, really appreciate

**Comment by tibewww** [comment]
Seems it still loading the video in 360 mode and not Cardboard :(, any reason ?

**Comment by tibewww** [comment]
Ok, I had it working with the following:

```
- (void) VRMode:(BOOL)enabled {
    if(true) {
        _isUsingCardboard = !_isUsingCardboard;
        _cardboardButton.selected = _isUsingCardboard;
        if (_isUsingCardboard) {
            [self removeGLKView];
            [self configureCardboardView];
        }
        else {
            _isUsingCardboard = NO;
        }

```

Thanks for all your help :)
