### ISSUE TITLE
播放器与陀螺仪旋转的bug

### ISSUE THREAD

**Issue by JiangangYang** [islate/SlateVideo360#11]
1.进入播放器界面全屏显示情况下，初始位置是错误的，需要将手机向上倾斜大概30°才是正常的角度

2.在全屏显示情况下，手机陀螺仪旋转与视频界面旋转是反向的，界面旋转没有和陀螺仪旋转方向一致、

我邮箱：18810626720@163.com 
![bug1](https://cloud.githubusercontent.com/assets/7603077/17010420/5ca07ff2-4f36-11e6-9880-f05343e3ed59.png)
![bug2](https://cloud.githubusercontent.com/assets/7603077/17010419/5c94225c-4f36-11e6-9cab-6ee3964f50f4.png)

**Comment by JiangangYang** [comment]
此bug还未修复？

**Comment by linyize** [comment]
你有没有修复的方案？ @yjg2014 
欢迎大家参与这个项目，可以自己fork出去，进行完善，再提交pullrequest

**Comment by stoneeagle** [comment]
这个初始位置是错的bug，还没有解啊
