### ISSUE TITLE
Size of VR view

### ISSUE THREAD

**Issue by SteveEdson** [islate/SlateVideo360#13]
On the iPhone 6s (although not on the simulator), the VR view doesn't cover the whole height of the screen. The faded lens boxes stop about 3/4 up the screen. Any idea why this would be?

**Comment by linyize** [comment]
I think it's the google cardboard SDK settings.

**Comment by Gail9527** [comment]
i have the same issue. it is right when the app is running in simulator.but if it is running in real device, the VR view doesn't cover the whole height of screen

**Comment by linyize** [comment]
![iphone6s](https://cloud.githubusercontent.com/assets/2630222/20515933/cab4f7c6-b0ce-11e6-852f-b69e662519aa.jpg)
@SteveEdson I run my example on iPhone6s and got this. Same as your condition?

**Comment by linyize** [comment]
@SteveEdson dancingalone provided a solution. I will update cardboardsdk and slatevideo360 pods, you can try again later.
