### ISSUE TITLE
pod 我实在用不来 使用淘宝镜像 搜索都搜不到

### ISSUE THREAD

**Issue by 931743010** [islate/SlateVideo360#14]
可以来一份完整版  百度网盘不；谢啦；我发现3/4 的问题 都是 说项目部完整；pod 不下来出问题
求完整 版  跪谢

**Comment by linyize** [comment]
http://7b1gcw.com1.z0.glb.clouddn.com/video360test.zip

**Comment by linyize** [comment]
pod 有个不好的地方，会把整个仓库取下来，hty的仓库太大了 快200兆，所以导致install很慢。网络不好就没办法了。
我试试另外建一个独立的仓库来做pod吧 @931743010

**Comment by 931743010** [comment]
@linyize  恩 下载可以了  谢谢啦
