### ISSUE TITLE
VR视频源的问题，2D转3D视频的解决方案

### ISSUE THREAD

**Issue by app111** [islate/SlateVideo360#17]
目前想到了2种：
1。服务器直接转，但带宽成本太高
2。客户端播放的时候实时转，楼主有没有这方面的研究，比如Opencv，OpenGL可以实现吗？

**Comment by linyize** [comment]
2D转3D是什么概念？
目前的主流方案都是一个2D视频（投影），在播放器端用openGL或者webGL变成3D

**Comment by app111** [comment]
本意是想着把2d的视频，在线边转3d边播放，给大伙的感觉都是3d的，可以支持class模式
openGL这方面没接触过，有没有例子可以参考呢？

**Comment by linyize** [comment]
目前vr实现方案基本就是你说的 2d->3d

**Comment by app111** [comment]
你的意思是我对2d视频源，播放的时候不做任何处理吗？问了其他人说用GPU处理每一帧

**Comment by linyize** [comment]
嗯 就是你说的 GPU实时渲染
