### ISSUE TITLE
iphone7 plus 真机 cardboard 模式下图像很小

### ISSUE THREAD

**Issue by Gail9527** [islate/SlateVideo360#26]
我在模拟器上运行时，cardboard模式下是正常的，但是当我在真机上运行时，cardboard模式下，视频窗口变小，我用 reveal2 观察，发现是glview里面绘制的窗口小
![wechatimg119](https://cloud.githubusercontent.com/assets/2200697/20511780/f8b75b46-b0b5-11e6-827e-1f1a17a4d69f.jpeg)

求解决

**Comment by linyize** [comment]
对不起  没有7 plus真机可以验证。麻烦你观察看看问题原因在哪

**Comment by linyize** [comment]
跟踪一下cardboardsdk里面CBDViewController 129行  UIScreen的大小是多少

**Comment by Gail9527** [comment]
更新： cardboardsdk里面的 ScreenParams.mm 中有一个计算 ppi的方法
`float ScreenParams::pixelsPerInch(UIScreen *screen)
{
    // Default iPhone retina pixels per inch
    float pixelsPerInch = 163.0f * 2;
    struct utsname sysinfo;
    if (uname(&sysinfo) == 0)
    {
        NSString *identifier = [NSString stringWithUTF8String:sysinfo.machine];
        NSArray *deviceClassArray =
  @[
    // iPads
  @{@"identifiers":
        @[@"iPad1,1",
          @"iPad2,1", @"iPad2,2", @"iPad2,3", @"iPad2,4",
          @"iPad3,1", @"iPad3,2", @"iPad3,3", @"iPad3,4",
          @"iPad3,5", @"iPad3,6", @"iPad4,1", @"iPad4,2"],
    @"pointsPerInch": @132.0f},
  // iPhones, iPad Minis and simulators
  @{@"identifiers":
        @[@"iPod5,1",
          @"iPhone1,1", @"iPhone1,2",
          @"iPhone2,1",
          @"iPhone3,1", @"iPhone3,2", @"iPhone3,3",
          @"iPhone4,1",
          @"iPhone5,1", @"iPhone5,2", @"iPhone5,3", @"iPhone5,4",
          @"iPhone6,1", @"iPhone6,2",
          @"iPhone7,1", @"iPhone7,2",
          @"iPad2,5", @"iPad2,6", @"iPad2,7",
          @"iPad4,4", @"iPad4,5",
          @"i386", @"x86_64"],
    @"pointsPerInch":  @163.0f } ];
        for (NSDictionary *deviceClass in deviceClassArray)
        {
            for (NSString *deviceId in deviceClass[@"identifiers"])
            {
                if ([identifier isEqualToString:deviceId])
                {
                    pixelsPerInch = [deviceClass[@"pointsPerInch"] floatValue] * _scale;
                    break;
                }
            }
        }
    }
    return pixelsPerInch;
}
`

这里没有对 iphone7 做判断，因此造成了 返回值 pixelsPerInch 的不正确 导致后面的计算出问题
不知道这个应该怎么修改？

**Comment by linyize** [comment]
厉害  @dancingalone   我刚才查了 谷歌sdk还没有新的提交。你可以补充一下修复的代码吗？我可以改到我fork的仓库里

**Comment by Gail9527** [comment]
update： 接上面的 在方法中添加对应的 identifier 解决了这个问题。附件是我修改后的 方法

`
float ScreenParams::pixelsPerInch(UIScreen *screen)
{
    // Default iPhone retina pixels per inch
    float pixelsPerInch = 163.0f * 2;
    struct utsname sysinfo;
    if (uname(&sysinfo) == 0)
    {
        NSString *identifier = [NSString stringWithUTF8String:sysinfo.machine];
        NSArray *deviceClassArray =
  @[
    // iPads
  @{@"identifiers":
        @[@"iPad1,1",
          @"iPad2,1", @"iPad2,2", @"iPad2,3", @"iPad2,4",
          @"iPad3,1", @"iPad3,2", @"iPad3,3", @"iPad3,4",
          @"iPad3,5", @"iPad3,6", @"iPad4,1", @"iPad4,2"],
    @"pointsPerInch": @132.0f},
  // iPhones, iPad Minis and simulators
  @{@"identifiers":
        @[@"iPod5,1",
          @"iPhone1,1", @"iPhone1,2",
          @"iPhone2,1",
          @"iPhone3,1", @"iPhone3,2", @"iPhone3,3",
          @"iPhone4,1",
          @"iPhone5,1", @"iPhone5,2", @"iPhone5,3", @"iPhone5,4",
          @"iPhone6,1", @"iPhone6,2",
          @"iPhone7,1", @"iPhone7,2",
          @"iPad2,5", @"iPad2,6", @"iPad2,7",
          @"iPad4,4", @"iPad4,5",
          @"iPhone8,1",@"iPhone8,2",
          @"iPhone9,1",@"iPhone9,2",
          @"iPhone9,1",@"iPhone9,2",
          @"i386", @"x86_64"],
    @"pointsPerInch":  @163.0f } ];
        for (NSDictionary *deviceClass in deviceClassArray)
        {
            for (NSString *deviceId in deviceClass[@"identifiers"])
            {
                if ([identifier isEqualToString:deviceId])
                {
                    pixelsPerInch = [deviceClass[@"pointsPerInch"] floatValue] * _scale;
                    break;
                }
            }
        }
    }
    return pixelsPerInch;
}`


替换 ScreenParams.mm 169行的方法就可以了

**Comment by linyize** [comment]
Great job! @dancingalone  
我将升级一下cardboardsdk和slatevideo360
