### ISSUE TITLE
Error when call presentViewController

### ISSUE THREAD

**Issue by TomasPangzi** [islate/SlateVideo360#29]
error: libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by linyize** [comment]
can u post more detail info of the exception?

**Comment by TomasPangzi** [comment]
I write a demo with SlateVideo360 and work find. but it can to a error when I integrate to my existing project. My existing project is portrait only by the way. When I present the Video360ViewController, it come to the error above. And this is the only exception I can see in my console.

**Comment by TomasPangzi** [comment]
sorry, my bad.
