### ISSUE TITLE
编译出错的问题

### ISSUE THREAD

**Issue by sacrtap** [islate/SlateVideo360#7]
hi，你好
我通过你的工程执行了pod升级
同时时修改了Podfile
target "video360test" do
pod ‘SlateVideo360’
end

然后再pod install
生成的工程都正常（包括video360test.xcworkspace等文件）。
但是在xcode编译过程也正常，向手机安装中出现了一个问题：
“The file “video360test.app” couldn’t be opened because you don’t have permission to view it.You don’t have permission.”
请问一下怎么解决呀？在线等！

附：
1）在解决编译过程中的报错时，我将targets-》Build Phases-》Compile Sources中的Items都删除的（原来默认里面都是导入的.m的头文件，我全部删掉后，编译就不报错了）
2）在targets-》Build Settings-》Build Options-》Compiler for C/C++/Objective-C 设置为“Default compiler（Apple LLVM7.1）”

**Comment by linyize** [comment]
传个你的demo工程到github上来看看

**Comment by linyize** [comment]
好的 我完善了一下demo的工程设置和podfile，请更新重试一下

**Comment by sacrtap** [comment]
已经解决啦。多谢。
