### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by SteveEdson** [islate/SlateVideo360#8]
Trying to run the example app, ran `pod install` and opened the workspace but i get the following error when trying to run:

```
duplicate symbol _uniforms in:
    /Users/steveedson/Library/Developer/Xcode/DerivedData/video360test-fsrndxbfleyrnqcligfvcfliqqwk/Build/Products/Debug-iphoneos/HTY360Player/libHTY360Player.a(HTYGLKVC.o)
    /Users/steveedson/Library/Developer/Xcode/DerivedData/video360test-fsrndxbfleyrnqcligfvcfliqqwk/Build/Products/Debug-iphoneos/SlateVideo360/libSlateVideo360.a(VideoRenderer.o)
ld: 1 duplicate symbol for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas? Thanks.

**Comment by kammodze** [comment]
I've resolved it temporarily by changing one of them name. In SlateVideo360's VideoRenderer.h rename all usages of 'uniform' to something else. 
Edit: I meant VideoRenderer.m

**Comment by SteveEdson** [comment]
Do you mean VideoRenderer.**m**? I can't see any usages in VideoRenderer.h,

Thanks.

**Comment by kammodze** [comment]
Oh, yes. Sorry :)

**Comment by SteveEdson** [comment]
How do I change this? The VideoRenderer.h is within the pod dependency, so once I change it, how do I point to my local copy?

Thanks

**Comment by linyize** [comment]
@SteveEdson I've changed the enum's name in VideoRenderer.m and push a new version 0.1.3. Plz update the pod.

@kammodze  Thanks.
