### ISSUE TITLE
Cannot decode - Demo app

### ISSUE THREAD

**Issue by SteveEdson** [islate/SlateVideo360#9]
Trying to run the demo app on a iPad running iOS 9. All I have done is cloned, installed the podfiles and changed the bundle identifier so I can install it to a device.

When selecting "Play File", I get a dialog pop up saying "Cannot Decode", "The media data could not be decoded. It may be damaged".

Any ideas?

**Comment by linyize** [comment]
May be the demo1.mp4 file is damaged during net tranfer? Can you clone a new working copy and try again?

**Comment by linyize** [comment]
Can I close this issue? @SteveEdson

**Comment by SteveEdson** [comment]
I don't think the file is corrupted, it works fine on the iPhone 6 simulator, but when I switch to the iPad 2 simulator, it cannot decode

**Comment by linyize** [comment]
no problem in my ipad2 simulator
